# Generated by Django 5.2.6 on 2025-10-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_bio_alter_profile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/default_avatars/017-black-panther.png', upload_to='avatars/'),
        ),
    ]
