# Generated by Django 5.2.6 on 2025-10-10 13:57

import utils.media_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=utils.media_utils.get_random_avatar, upload_to='avatars/'),
        ),
    ]
