# Generated by Django 5.2.6 on 2025-10-10 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
