# Generated by Django 5.2.6 on 2025-10-17 08:23

import blog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default=blog.utils.get_random_thumbnail, upload_to='thumbnails/'),
        ),
    ]
