# Generated by Django 5.2.6 on 2025-10-10 13:57

import utils.media_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default=utils.media_utils.get_random_thumbnail, upload_to='thumnails/'),
        ),
    ]
